# Prompt format...
# - Directory section with blue background and light text
# - Git branch section with yellow background and dark text
# - Git status and metrics in the same yellow background
# - Clean separator between sections
# - Final space for command input
# - Disabled line break for compactness
format = """\
$directory\
[](fg:#3B76F0 bg:#4dff4d)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#4dff4d bg:#030B16)\
[ ]('')\
"""

right_format = """\
$character\
$cmd_duration\
$time\
"""

[line_break]
disabled = true

add_newline = true

[cmd_duration]
disabled = false
min_time = 2000
show_milliseconds = false
format = "[  $duration ]($style)"
style = "fg:bright-white bg:18"

[directory]
format = "[$path ]($style)"
truncate_to_repo = true
truncation_length = 3
truncation_symbol = "…/"
style = "fg:#E4E4E4 bg:#3B76F0"

[time]
disabled = false
format = "[$time]($style) "
style = "dimmed white"
time_format = "%T" # %R no seconds, %T seconds

[git_branch]
disabled = false
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:#1C3A5E bg:#4dff4d"

[git_status]
disabled = false
format = '[$all_status$ahead_behind]($style)'
style = "fg:#1C3A5E bg:#f9e71f"
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '[⇕⇡${ahead_count}⇣${behind_count}](fg:#1C3A5E bg:#f9e71f)'
use_git_executable = true

[git_metrics]
disabled = true
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#1C3A5E bg:#f9e71f"
deleted_style = "fg:bright-red bg:235"

[character]
disabled = false
success_symbol = '[](bold green) '
error_symbol = '[✗](bold red) '
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'
